apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-sync-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: group-sync-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-prod/group-sync-operator
    repoURL:  git@github.com:stakater/openshift-infra-gitops-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
