apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-registry
  namespace: openshift-gitops
spec:
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-prod/image-registry
    repoURL:  git@github.com:stakater/openshift-infra-gitops-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
