kind: Namespace
apiVersion: v1
metadata:
  name: openshift-gitops
  labels:
    kubernetes.io/metadata.name: openshift-gitops
    openshift.io/cluster-monitoring: 'true'
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/node-selector: "node-role.kubernetes.io/infra="
