apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/auth

resources:
  - org-ca-config-map.yaml
  - htpasswd-sealed.yaml


patchesStrategicMerge:
  - bindpassword-sealed.yaml
  - oauth.yaml
