kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-bindings
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: <placeholder>  # LDAP Group for administrators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
