apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/reloader

patches:
  - target:
      kind: Namespace
      name: stakater-reloader
    patch: |
      - op: remove
        path: /metadata/annotations/openshift.io~1node-selector