apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-bindings
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: TODO  # LDAP Group for administrators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
