apiVersion: v1
kind: ConfigMap
metadata:
  name: org-ca-config-map
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDEDC...
    -----END CERTIFICATE-----
