apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-group-sync
  namespace: group-sync-operator
spec:
  encryptedData:
    password: ...
    username: ...
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ldap-group-sync
      namespace: group-sync-operator
