apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-backup
  namespace: openshift-gitops
spec:
  destination:
    namespace: ocp-backup-etcd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-dev/etcd-backup
    repoURL:  git@github.com:stakater/openshift-infra-gitops-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
