apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-dev/rbac
    repoURL:  https://github.com/stakater/openshift-infra-gitops-example
    targetRevision: basic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
