apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: custom-kubelet
spec:
  machineConfigPoolSelector:
    matchLabels:
      managed.openshift.io/custom-kubelet: ""
  kubeletConfig:
    kubeReserved:   # Reserve for kube processes
      cpu: "500m"
      memory: "1Gi"
      ephemeral-storage: "1Gi"
    systemReserved: # Reserve for OS processes
      cpu: "500m"
      memory: "2Gi"
      ephemeral-storage: "1Gi"
    evictionHard:   # Will evict pods when only given resources are left on a node
      memory.available:  "2Gi"
      nodefs.available: "10%"